export const japanMejorCities = [
  { name: "札幌", id: "sapporo" },
  { name: "宮城", id: "miyagi" },
  { name: "東京", id: "tokyo" },
  { name: "川崎", id: "kawasaki" },
  { name: "横浜", id: "yokohama" },
  { name: "名古屋", id: "nagoya" },
  { name: "京都", id: "kyoto" },
  { name: "大阪", id: "osaka" },
  { name: "高知", id: "kochi" },
  { name: "広島", id: "hirosima" },
  { name: "福岡", id: "fukuoka" },
  { name: "鹿児島", id: "kagoshima" },
  { name: "沖縄", id: "okinawa" },
];
